In [36]:
import pandas as pd
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a.ndim
a.shape

(2, 3)

### Array()

In [ ]:
a = np.array([1,2,3,4.0],int)
a.dtype
a

### LINSPACE(START,END,PARTS<default 50>)

In [13]:
arr = np.linspace(0,15,16)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

### ARANGE(START,END,STEP)

In [15]:
arr = np.arange(2,20,3)
arr

array([ 2,  5,  8, 11, 14, 17])

### LOGSPACE()

In [25]:
arr = np.logspace(1,10,5)
for i in arr:
    print(i)

10.0
1778.2794100389228
316227.7660168379
56234132.51903491
10000000000.0


In [26]:
arr[2]

316227.7660168379

### ZEROS() , ONES()

In [27]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])