In [25]:
from numpy import *
import math as math

In [7]:
arr = array([1,2,3,4])
arr = arr ** 2
arr

array([ 1,  4,  9, 16], dtype=int32)

In [9]:
arr = arr +3
arr

array([ 7, 10, 15, 22], dtype=int32)

In [11]:
arr1 = array([1,2,3,4])
arr2 = array([3,7,4,8])
arr1 + arr2

array([ 4,  9,  7, 12])

In [12]:
arr = array([1,2,3,4])
sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [13]:
log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [15]:
sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [29]:
sin(math.pi/2)

1.0

In [30]:
sum(arr)

10

In [31]:
mean(arr)

2.5

In [35]:
concatenate([arr1,arr2])

array([1, 2, 3, 4, 3, 7, 4, 8])

### COPY ARRAY

In [67]:
arr1 = array([3,7,4,8])
arr2 = arr1

In [50]:
arr1

array([3, 7, 4, 8])

In [51]:
arr2

array([3, 7, 4, 8])

In [52]:
id(arr1)

97926384

In [53]:
id(arr2)

97926384

In [55]:
arr2[1] = 333
arr2

array([  3, 333,   4,   8])

In [56]:
arr1

array([  3, 333,   4,   8])

### DEEPCOPY

In [68]:
arr2 = arr1.copy()
arr2

array([3, 7, 4, 8])

In [69]:
arr2[1] = 333
arr2

array([  3, 333,   4,   8])

In [70]:
arr1

array([3, 7, 4, 8])

### SHALLOW COPY

In [71]:
arr1 = array([3,7,4,8])
arr2 = arr1.view()
arr2[1] = 333
arr2

array([  3, 333,   4,   8])

In [73]:
arr1

array([  3, 333,   4,   8])

In [74]:
a=array([41,22,39,57,12])
p=a[0]
for e in a:
    if e>=p:
        p=e
print(p)

57
