In [1]:
from numpy import *

In [11]:
arr1 = array([
    [1,2,3,10,20,30],
    [4,5,6,40,50,60]
])
arr1

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [12]:
arr1.dtype

dtype('int32')

In [13]:
arr1.size

12

In [14]:
arr1.shape

(2, 6)

In [15]:
arr1.ndim

2

In [16]:
arr2 = arr1.flatten()
arr2

array([ 1,  2,  3, 10, 20, 30,  4,  5,  6, 40, 50, 60])

In [18]:
arr3 = arr2.reshape(3,2,2)
arr3

array([[[ 1,  2],
        [ 3, 10]],

       [[20, 30],
        [ 4,  5]],

       [[ 6, 40],
        [50, 60]]])

In [19]:
arr3 = arr2.reshape(2,3,2)
arr3

array([[[ 1,  2],
        [ 3, 10],
        [20, 30]],

       [[ 4,  5],
        [ 6, 40],
        [50, 60]]])

In [22]:
m = matrix(arr1)
m

matrix([[ 1,  2,  3, 10, 20, 30],
        [ 4,  5,  6, 40, 50, 60]])

In [32]:
m = matrix("1 2 3;4 5 6;7 8 9")
m[1,1]

5

In [26]:
m.diagonal()

matrix([[1, 5, 9]])

In [27]:
m.max()

9

In [28]:
m1 = matrix("1 2 3;4 5 6;7 8 9")
m2 = matrix("1 2 3;4 5 6;7 8 9")

In [29]:
m1 + m2

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [30]:
m1 * m2

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])